feat:добавление item и user, первая итерация
vitaliibredun/java-shareit pull request #1
Opened 2023-02-19 11:55 UTC by vitaliibredun

2023-02-20 15:06 UTC, ErkinKasymaliev requested changes
Привет, оставил комменты!
Основная проблема везде валидация всего.
Валидировать надо входные данные, то есть DTO - через аннотации, в сервисах и так далее. И если все норм, то маппить в модели и передавать в репозиторий - где уже проверки на валидаций быть не должно

2023-02-20 15:06 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/dao/impl/UserStorageInMemory.java
> +        boolean updateUserNameAndEmail = (user.getName() != null) && (user.getEmail() != null);
эти все проверки же вы сервисе сделали через валидационные классы, зачем вы дублируете?

2023-02-20 15:06 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/dao/impl/ItemStorageInMemory.java
> +    private final Map<Integer, List<Item>> itemsByUsers = new HashMap<>();
лучше items также отдедльно хранить Map<Integer, Item> items

2023-02-20 15:06 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/dao/impl/ItemStorageInMemory.java
> +        boolean updateItem = (item.getName() != null)
опять же дублируете валидацию, сюда уже должны приходить данные после прохождения валидации в сервисах

2023-02-20 15:06 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/dao/impl/ItemStorageInMemory.java
> +        return itemsByUsers.values()
как я вначале класса написал создайте отдельный map для хранения items и вытаскивайте оттуда

2023-02-20 15:06 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/dao/impl/ItemStorageInMemory.java
> +        return itemsByUsers.get(userId);
как я вначале класса написал создайте отдельный map для хранения items и вытаскивайте оттуда

2023-02-20 15:06 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/dao/impl/ItemStorageInMemory.java
> +        return itemsByUsers.values()
как я вначале класса написал создайте отдельный map для хранения items и вытаскивайте оттуда

2023-02-20 21:13 UTC, vitaliibredun commented on src/main/java/ru/practicum/shareit/exceptions/NameFieldEmptyException.java
> +public class NameFieldEmptyException extends RuntimeException {
cделал, спасибо. Только оставил EmailAlreadyExistException т.к. для тестов нужна обработка этого исключения

2023-02-20 21:24 UTC, vitaliibredun commented on src/main/java/ru/practicum/shareit/user/dao/impl/UserStorageInMemory.java
> +        boolean updateUserNameAndEmail = (user.getName() != null) && (user.getEmail() != null);
делаю для обновления определённого поля. Не знаю как иначе можно реализовать

2023-02-20 21:29 UTC, vitaliibredun commented on src/main/java/ru/practicum/shareit/validation/UserValidation.java
> +        boolean incorrectType = Objects.requireNonNull(userDto.getEmail()).contains("@");
понимаю, согласен. Я просто знаю что будут появляться ещё условия проверки входных данных. При текущей реализации я буду просто добавлять новые методы в классы UserValidation и ItemValidation и это будут 2 класса которые отвечают за все проверки на валидацию.
А если буду использовать аннотации, то мне будет необходимо писать методы проверки валидация или создавать кастомные аннотации помимо существующих в библиотеках. Просто мне кажется это не удобным для чтения кода и работы при новых расширенных проверки на валидацию.
Верно ли я рассуждаю?

2023-02-20 21:31 UTC, vitaliibredun commented on src/main/java/ru/practicum/shareit/item/dao/impl/ItemStorageInMemory.java
> +        boolean updateItem = (item.getName() != null)
реализовал для проверки выбора поля обновления исходя из запроса. Не знаю как иначе реализовать

2023-02-20 21:36 UTC, vitaliibredun commented on src/main/java/ru/practicum/shareit/item/dao/impl/ItemStorageInMemory.java
> +    private final Map<Integer, List<Item>> itemsByUsers = new HashMap<>();
думал над этой реализацией, просто решил что слишком часто повторяется id данные по модели item, сейчас в модели item имеется поле для хранения id, получается если делать мапу вместо коллекции то у нас будет ключом являться id определённого item но и сам класс item имеет поле с id. 
ИЛи правильно понимаю реализация с мапой позволит оптимизировать алгоритм поиска?

2023-02-21 11:04 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/dao/impl/ItemStorageInMemory.java
> +    private final Map<Integer, List<Item>> itemsByUsers = new HashMap<>();
это дополнительная мапа оптимизирует и поиск и легкость чтения кода

2023-02-21 11:07 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/dao/impl/ItemStorageInMemory.java
> +        boolean updateItem = (item.getName() != null)
аа, понял, тогда в принципе подойдет

2023-02-21 11:55 UTC, vitaliibredun commented on src/main/java/ru/practicum/shareit/item/dao/impl/ItemStorageInMemory.java
> +    private final Map<Integer, List<Item>> itemsByUsers = new HashMap<>();
понял, спасибо большое

2023-02-22 07:19 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-02-22 09:36 UTC, vitaliibredun commented
> привет, работа принята

привет
спасибо

2023-02-22 09:38 UTC, merged