feat: add bookings
vitaliibredun/java-shareit pull request #2
Opened 2023-03-13 20:44 UTC by vitaliibredun

2023-03-13 21:02 UTC, vitaliibredun commented
по тестам так понимаюсь не проблема, их почему-то обновляют уже не первый раз и не предупреждают. Я уже использовал те, что были обновлены не так давно да и в ide запускал verify чтобы уже максимально всё по проекту было проверено

2023-03-15 04:50 UTC, ErkinKasymaliev requested changes
привет! 
неплохая работа, но есть моменты:
я оставил коммент в Booking.java - и он касается всех моделей в проекте.
Также попробуй использовать mapStruct в мапперах и попробуй использовать в DTO аннотации для валидации.
Насчет тестов - они должны быть всегда зелеными, иначе работа не будет принята.

2023-03-15 04:50 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/dto/mapper/BookingMapper.java
> +public class BookingMapper {
может заюзаете MapStruct?

2023-03-15 04:50 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private Integer itemId;
здесь же надо использовать Item item с аннотацией @ManyToOne, как у много booking может быть у одного item.  Вы должны были пройти уже @ManyToOne, @OneToMany, @JoinColumn

2023-03-15 04:50 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>      private Integer booker;
здесь же надо использовать Booker booket item с аннотацией @ManyToOne, как у много booking может быть у одного booker. Вы должны были пройти уже @ManyToOne, @OneToMany, @JoinColumn

2023-03-15 04:50 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingServiceImpl.java
> +        Item item = itemRepository.findById(booking.getItemId()).orElseThrow();
когда вы исправите комменты которые я оставил в Booking.java, то строчки 61 и 62 не нужны будут, так как после Booking booking = bookingRepository.save(bookingToRepository); booking уже будет содержать поля Booker booker, Item item

2023-03-15 04:50 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/comments/model/Comment.java
> +    private Integer itemId;
смотрите комменты в Booking.java

2023-03-15 04:50 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/comments/model/Comment.java
> +    private Integer authorId;
смотрите комменты в Booking.java

2023-03-15 04:50 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private Integer owner;
смотрите комменты в Booking.java

2023-03-15 04:50 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Integer requestId;
смотрите комменты в Booking.java

2023-03-15 04:50 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
>      private Integer requestor;
смотрите комменты в Booking.java

2023-03-18 09:45 UTC, vitaliibredun commented
> привет!
> неплохая работа, но есть моменты:
> я оставил коммент в Booking.java - и он касается всех моделей в проекте.
> Также попробуй использовать mapStruct в мапперах и попробуй использовать в DTO аннотации для валидации.
> Насчет тестов - они должны быть всегда зелеными, иначе работа не будет принята.

привет
спасибо большое за замечания
поправил

2023-03-18 10:23 UTC, ErkinKasymaliev requested changes
привет, в принципе норм, но тесты не проходят постмана. Их надо поправить

2023-03-18 10:30 UTC, vitaliibredun commented
> привет, в принципе норм, но тесты не проходят постмана. Их надо поправить

спасибо
да, вот уже пытаюсь у куратора узнать в чём дело. Не понимаю просто что не так. Читаю логи, звучит так, что мне нужно обновить har-validator@5.1.5 и uuid@3.4.0
но я не понимаю что это и то ли это)
я тогда как всё сделаю, отпишусь

2023-03-18 21:00 UTC, vitaliibredun commented
> привет, в принципе норм, но тесты не проходят постмана. Их надо поправить

была удивительная ошибка, я даже не мог представить что из-за этого тесты не проходили на gitHub

2023-03-19 09:21 UTC, ErkinKasymaliev approved these changes
привет, молодец, теперь все норм!

2023-03-19 12:43 UTC, merged