feat: added item-request
vitaliibredun/java-shareit pull request #3
Opened 2023-04-03 12:28 UTC by vitaliibredun

2023-04-04 15:09 UTC, ErkinKasymaliev requested changes
Привет, хорошая работа!
но давайте в репозиториях будем юзать Pageable

2023-04-04 15:09 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .findAllByOwner(userId).stream().skip(from).limit(size).collect(Collectors.toList());
заюзагйте Pageable в репозитории вместо skip и limit

2023-04-04 17:10 UTC, vitaliibredun commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .skip(from)
привет
изначально планировал с ним делать и писал, но тогда код работает не корректно
я так понимаю я реализую аргумент методов такого плана?
findUser(userId, PageRequest.of(from/size, size)

но тогда код работает не верно, то есть тесты пройдут postman но по факту по ТЗ нам нужно не постранично выдавать данные а именно от определённого индекса элемента и до определённого размера списка

поэтому не нашёл применения для Pageable в данном случае

2023-04-04 19:52 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .skip(from)
это и есть Pageable

2023-04-04 20:11 UTC, vitaliibredun commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .skip(from)
но ведь я буквально проверял по коду
допустим если есть список с id
56813

и я хочу получить при помощи Pageable данные от 1 элемента, размером в 4 элемента
то у меня должно в данном случае выводиться в таком порядке
5681

если я хочу получить данные от 3 элемента с размером 2
то у меня должно в данном случае выводиться в таком порядке
83
1

хотя если я применю Pageable при запросе аргумента from/size, size
то у меня будет расчёт не от 3 элемента а от второго
то есть
68
13

у нас тесты в postman составлены на 1 кейс и он получается успешным
хотя относительно проекта и ТЗ ведь не выполняется функциональность


извиняюсь что много текста)
просто поэтому не стал использовать к сожалению

или не так рассуждаю?

2023-04-04 20:17 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .skip(from)
допустим у вас таблице id от 1 до 1000, на контроллер вам приходит from 1, size 100, то придут id с 1 до 101, from 160, size 50, то с 160 по 209. Вы же в оперативную память загружаете все данные, и там уже skip и limit, но опять же - это в оперативке, а должно выполняться на стороне бд

2023-04-05 23:34 UTC, vitaliibredun commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .findAllByOwner(userId).stream().skip(from).limit(size).collect(Collectors.toList());
поправил код
спасибо
жаль что просто тесты не корректные в postman)

2023-04-06 09:19 UTC, ErkinKasymaliev approved these changes
привет, теперь работа огонь!
работа принята

2023-04-06 09:28 UTC, vitaliibredun commented
> привет, теперь работа огонь!
> работа принята

спасибо
спасибо большое за ревью

2023-04-06 09:28 UTC, merged