feat: added docker
vitaliibredun/java-shareit pull request #5
Opened 2023-04-12 12:02 UTC by vitaliibredun

2023-04-13 06:38 UTC, ErkinKasymaliev requested changes
привет, работа хорошая.
оставил 1 коммент и почему у тебя всегда сборка падает? ее надо починить

2023-04-13 06:38 UTC, ErkinKasymaliev commented on server/pom.xml
> +            <groupId>org.springframework.boot</groupId>
валидации входных данных в контроллер в сервере быть не должно, даже в pom.xml

2023-04-13 06:49 UTC, vitaliibredun commented
> привет, работа хорошая.
> оставил 1 коммент и почему у тебя всегда сборка падает? ее надо починить

привет, спасибо
да вот ковыряю проект сутки уже, разбираюсь, локально у меня всё проходит по тестам и в докере тоже, а на гитхабе либо всё валится либо 12 тестов(полей) не проходит

2023-04-13 23:04 UTC, vitaliibredun commented
ну наконец-то
проблема была там, где бы даже не подумал искать

2023-04-14 04:40 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-04-14 07:50 UTC, merged